/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CotButton {
    }
    interface CotTextbox {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCotButtonElement extends Components.CotButton, HTMLStencilElement {
    }
    var HTMLCotButtonElement: {
        prototype: HTMLCotButtonElement;
        new (): HTMLCotButtonElement;
    };
    interface HTMLCotTextboxElement extends Components.CotTextbox, HTMLStencilElement {
    }
    var HTMLCotTextboxElement: {
        prototype: HTMLCotTextboxElement;
        new (): HTMLCotTextboxElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cot-button": HTMLCotButtonElement;
        "cot-textbox": HTMLCotTextboxElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CotButton {
    }
    interface CotTextbox {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cot-button": CotButton;
        "cot-textbox": CotTextbox;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cot-button": LocalJSX.CotButton & JSXBase.HTMLAttributes<HTMLCotButtonElement>;
            "cot-textbox": LocalJSX.CotTextbox & JSXBase.HTMLAttributes<HTMLCotTextboxElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
